---
- name: Setup Arch Linux system
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files: config.yaml

  handlers:
    - import_tasks: handlers.yaml

  tasks:
    - name: Add kernel parameters at boot
      become: yes
      lineinfile:
        path: /boot/loader/entries/arch.conf
        regexp: ^options ((.(?!quiet splash))*)$
        line: options \1 quiet splash
        backrefs: yes

    - name: Setup network
      tags: [network]
      become: yes
      block:
        - name: Add systemd-networkd config
          template:
            src: templates/systemd/network/20-wired.network.j2
            dest: /etc/systemd/network/20-wired.network
          notify: Restart systemd-networkd

        - name: Enable systemd-networkd and systemd-resolved
          service:
            name: '{{ item }}'
            enabled: yes
          loop:
            - systemd-networkd
            - systemd-resolved

    - name: Ensure system has correct timezone
      timezone: name={{ timezone }}

    - name: Adjust pacman options
      become: yes
      lineinfile:
        path: /etc/pacman.conf
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      loop:
        - regexp: ^#?Color$
          line: Color
        - regexp: ^#?ParallelDownloads =
          line: ParallelDownloads = {{ pacman.parallel_downloads }}

    - name: Synchronize database and upgrade packages
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install essential packages
      become: yes
      pacman:
        name:
          - git
          - python
          - neovim
          - docker
          - wayland
          - polkit
          - polkit-gnome
          - pipewire
          - pipewire-pulse
          - wireplumber
          - noise-suppression-for-voice
          - pavucontrol
          - sway
          - swaybg
          - waybar
          - xorg-xwayland
          - rofi
          - otf-font-awesome
          - dunst
          - libnotify
          - dex
          - zsh
          - tmux
          - alacritty
          - ttf-sourcecodepro-nerd
          - firefox
          - mpv
          - sudo
          - openssh
          - p7zip
          - xdg-user-dirs   # the service is enabled automatically
          - stow
          - gnome-keyring
          - libsecret
          - greetd
        state: present

    - name: Install AUR packages
      kewlfft.aur.aur:
        name:
          - kmonad-bin
          - flavours
        state: present

    - name: Add applications
      copy:
        src: files/applications/
        dest: ~/.local/share/applications/

    - name: Add autostart applications
      copy:
        src: files/autostart/
        dest: ~/.config/autostart/

    - name: Setup greetd
      become: yes
      lineinfile:
        path: /etc/greetd/config.toml
        regexp: ^command =
        line: command = "agreety --cmd sway"

    - name: Enable and start greetd
      become: yes
      service:
        name: greetd
        state: started
        enabled: yes

    - name: Setup bluetooth
      tags: [bluetooth]
      block:
        - name: Install bluetooth packages
          become: yes
          pacman:
            name:
              - bluez
              - bluez-utils
              - blueman

        - name: Enable fast connectable bluetooth
          become: yes
          lineinfile:
            path: /etc/bluetooth/main.conf
            regexp: '#?FastConnectable ='
            line: 'FastConnectable = true'

        - name: Enable bluetooth
          become: yes
          service:
            name: bluetooth
            enabled: yes
      notify: Restart bluetooth

    - tags: [user, never]
      block:
        - name: Setup sudo
          become: yes
          lineinfile:
            path: /etc/sudoers.d/main
            line: '%wheel ALL=(ALL) ALL'
            mode: 0440
            create: yes
            validate: visudo --check --file %s

        - name: Create user
          become: yes
          user:
            name: '{{ user }}'
            state: present
            shell: /bin/zsh
            groups:
              - wheel
              - docker
            append: yes
            generate_ssh_key: yes
            ssh_key_type: ed25519

    - name: Setup dotfiles
      block:
        - name: Clone dotfiles repository
          git:
            repo: https://github.com/italovieira/dotfiles.git
            dest: '{{ dotfiles_path }}'
            update: no
        - name: Put dotfiles symlinks in the target paths
          command:
            cmd: stow --verbose=2 {{ item }}
            chdir: '{{ dotfiles_path }}'
          loop:
            - zsh
            - git
            - nvim
            - tmux
            - sway
            - waybar
            - rofi
            - alacritty
            - kmonad
            - flavours
            - dunst
          register: stow
          changed_when: '"--- Skipping" not in stow.stderr'

    - name: Setup automatic keyring unlocking using PAM
      become: yes
      lineinfile:
        path: /etc/pam.d/greetd
        insertafter: '{{ item.insertafter }}'
        line: '{{ item.line }}'
      loop:
        - insertafter: '^auth'
          line: auth       optional     pam_gnome_keyring.so
        - insertafter: '^session'
          line: session    optional     pam_gnome_keyring.so auto_start

    - name: Setup GNOME Keyring
      copy:
        src: files/systemd/user/gnome-keyring-daemon.service.d/override.conf
        dest: ~/.config/systemd/user/gnome-keyring-daemon.service.d/
      notify: Reload systemd user daemon

    - name: Export env to SSH Agent socket
      lineinfile:
        path: ~/.zprofile
        line: export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/keyring/ssh


    - name: Setup kmonad
      tags: [keyboard]
      block:
        - name: Add udev rules
          become: yes
          copy:
            src: files/udev/rules.d/
            dest: /etc/udev/rules.d/
          notify: Reload udev rules

        - name: Create kmonad config path
          become: yes
          file:
            path: /etc/kmonad/
            state: directory

        - name: Add kmonad config
          become: yes
          file:
            src: /home/italo/.config/kmonad/keychron-k12.kbd
            dest: /etc/kmonad/config.kbd
            state: link

        - name: Enable kmonad service
          become: yes
          service:
            name: kmonad
            enabled: yes

      notify: Restart kmonad


    - name: Add Pipewire RNNoise input source
      copy:
        src: files/pipewire/source-rnnoise.conf
        dest: ~/.config/pipewire/pipewire.conf.d/
      notify: Restart pipewire
