---
- name: Setup Arch Linux system
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files: config.yaml

  handlers:
    - import_tasks: handlers.yaml

  tasks:
    - name: Add kernel parameters at boot
      lineinfile:
        path: /boot/loader/entries/arch.conf
        regexp: ^options ((.(?!quiet splash))*)$
        line: options \1 quiet splash
        backrefs: yes
      become: yes

    - name: Setup network
      tags: [network]
      become: yes
      block:
        - name: Add systemd-networkd config for Ethernet adapter
          template:
            src: templates/systemd/network/10-wired.network.j2
            dest: /etc/systemd/network/10-wired.network
          notify: Restart systemd-networkd

        - name: Add systemd-networkd config for wireless adapter
          template:
            src: templates/systemd/network/20-wireless.network.j2
            dest: /etc/systemd/network/20-wireless.network
          notify: Restart systemd-networkd

        - name: Enable systemd-networkd and systemd-resolved
          service:
            name: '{{ item }}'
            enabled: yes
          loop:
            - systemd-networkd
            - systemd-resolved

    - name: Ensure system has correct timezone
      timezone: name={{ timezone }}
      become: yes

    - name: Adjust pacman options
      become: yes
      lineinfile:
        path: /etc/pacman.conf
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      loop:
        - regexp: ^#?Color$
          line: Color
        - regexp: ^#?ParallelDownloads =
          line: ParallelDownloads = {{ pacman.parallel_downloads }}

    - name: Synchronize database and upgrade packages
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install essential packages
      become: yes
      pacman:
        name:
          - git
          - python
          - neovim
          - man-db
          - man-pages
          - wayland
          - polkit
          - polkit-gnome
          - pipewire
          - pipewire-pulse
          - wireplumber
          - noise-suppression-for-voice
          - pavucontrol
          - hyprland
          - swaybg
          - waybar
          - grim
          - slurp
          - wl-clipboard
          - xorg-xwayland
          - xdg-desktop-portal-hyprland
          - otf-font-awesome
          - dunst
          - libnotify
          - dex
          - zsh
          - tmux
          - alacritty
          - ttf-sourcecodepro-nerd
          - firefox
          - mpv
          - sudo
          - openssh
          - p7zip
          - xdg-user-dirs   # the service is enabled automatically
          - xdg-utils       # for xdg-open
          - stow
          - gnome-keyring
          - gcr-4           # see https://wiki.archlinux.org/index.php?title=GNOME/Keyring&oldid=801104#SSH_keys
          - libsecret
          - greetd
          - power-profiles-daemon
        state: present

    - name: Install AUR packages
      kewlfft.aur.aur:
        name:
          - rofi-lbonn-wayland
        state: present

    - name: Install some Rust packages
      block:
        - name: Install packages using cargo
          community.general.cargo:
            name: '{{ rust_packages }}'
        - name: Create packages symlink to ~/.local/bin/
          file:
            state: link
            src: '~/.cargo/bin/{{ item }}'
            dest: ~/.local/bin/{{ item }}
          loop:
            '{{ rust_packages }}'
      vars:
        rust_packages: [tinty]

    - name: Add applications
      copy:
        src: files/applications/
        dest: ~/.local/share/applications/

    - name: Add autostart applications
      copy:
        src: files/autostart/
        dest: ~/.config/autostart/

    - name: Create hyprland executable with custom environments
      become: yes
      copy:
        src: files/usr/local/bin/hyprland-run
        dest: /usr/local/bin/hyprland-run
        mode: 0755

    - name: Setup greetd
      become: yes
      lineinfile:
        path: /etc/greetd/config.toml
        regexp: ^command =
        line: command = "agreety --cmd hyprland-run"

    - name: Enable and start greetd
      become: yes
      service:
        name: greetd
        state: started
        enabled: yes

    - name: Setup bluetooth
      tags: [bluetooth]
      block:
        - name: Install bluetooth packages
          become: yes
          pacman:
            name:
              - bluez
              - bluez-utils
              - blueman

        - name: Enable fast connectable bluetooth
          become: yes
          lineinfile:
            path: /etc/bluetooth/main.conf
            regexp: '#?FastConnectable ='
            line: 'FastConnectable = true'

        - name: Enable bluetooth
          become: yes
          service:
            name: bluetooth
            enabled: yes
      notify: Restart bluetooth

    - tags: [user, never]
      block:
        - name: Setup sudo
          become: yes
          lineinfile:
            path: /etc/sudoers.d/main
            line: '%wheel ALL=(ALL) ALL'
            mode: 0440
            create: yes
            validate: visudo --check --file %s

        - name: Create user
          become: yes
          user:
            name: '{{ user }}'
            state: present
            shell: /bin/zsh
            groups:
              - wheel
              - docker
            append: yes
            generate_ssh_key: yes
            ssh_key_type: ed25519

    - name: Setup dotfiles
      block:
        - name: Clone dotfiles repository
          git:
            repo: https://github.com/italovieira/dotfiles.git
            dest: '{{ dotfiles_path }}'
            update: no
        - name: Put dotfiles symlinks in the target paths
          command:
            cmd: stow --verbose=2 {{ item }}
            chdir: '{{ dotfiles_path }}'
          loop:
            - zsh
            - git
            - nvim
            - tmux
            - sway
            - waybar
            - rofi
            - alacritty
            - kmonad
            - dunst
          register: stow
          changed_when: '"--- Skipping" not in stow.stderr'
      tags: [dotfiles]

    - name: Setup automatic keyring unlocking using PAM
      become: yes
      lineinfile:
        path: /etc/pam.d/greetd
        insertafter: '{{ item.insertafter }}'
        line: '{{ item.line }}'
      loop:
        - insertafter: '^auth'
          line: auth       optional     pam_gnome_keyring.so
        - insertafter: '^session'
          line: session    optional     pam_gnome_keyring.so auto_start

    - name: Setup GNOME Keyring
      copy:
        src: files/systemd/user/gnome-keyring-daemon.service.d/override.conf
        dest: ~/.config/systemd/user/gnome-keyring-daemon.service.d/
      notify: Reload systemd user daemon

    - name: Export env to SSH Agent socket
      lineinfile:
        path: ~/.zprofile
        line: export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh

    - name: Enable gcr SSH agent
      systemd:
        name: gcr-ssh-agent.socket
        enabled: yes
        scope: user

    - name: Add Pipewire RNNoise input source
      copy:
        src: files/pipewire/source-rnnoise.conf
        dest: ~/.config/pipewire/pipewire.conf.d/
      notify: Restart pipewire


    - name: Set GTK theme
      command: '{{ item }}'
      loop:
        - gsettings set org.gnome.desktop.interface gtk-theme '{{ gtk_theme }}'
        - gsettings set org.gnome.desktop.interface color-scheme prefer-dark
      tags: theme

    - name: Switch monitor input when keyboard gets plugged in
      tags: monitor
      block:
        - name: Add udev rule
          become: yes
          copy:
            src: files/udev/rules.d/99-switch_input.keyboard_plugged.rules
            dest: /etc/udev/rules.d/
          notify: Reload udev rules

        - name: Copy script to switch input
          become: yes
          copy:
            src: files/usr/local/bin/switch-monitor
            dest: /usr/local/bin/

    - name: Install and enable nftables
      block:
        - name: Install iptables-nft
          become: yes
          pacman:
            name: iptables-nft
            state: present

        - name: Ensure nftables service is enabled
          become: yes
          systemd:
            name: nftables
            state: started
            enabled: true
