---
- name: Setup ArchLinux system
  hosts: localhost

  vars:
    dotfiles_path: ~/dotfiles/
    user: italo

  tasks:
    - name: Synchronize database and upgrade packages
      become: true
      pacman:
        update_cache: true
        upgrade: true

    - name: Install essential packages
      become: true
      pacman:
        name:
          - git
          - python
          - neovim
          - docker
          - wayland
          - pipewire
          - sway
          - waybar
          - dunst
          - zsh
          - tmux
          - alacritty
          - firefox
          - mpv
          - sudo
          - openssh
          - p7zip
          - stow
        state: present

    - name: Setup sudo
      become: true
      lineinfile:
        path: /etc/sudoers.d/main
        line: '%wheel ALL=(ALL) ALL'
        mode: 0440
        create: yes
        validate: visudo --check --file %s

    - name: Create user
      become: true
      user:
        name: '{{ user }}'
        state: present
        groups:
          - wheel
          - docker
        append: yes
        generate_ssh_key: yes
        ssh_key_type: ed25519

    - name: Setup dotfiles
      become: yes
      become_user: '{{ user }}'
      block:
        - name: Clone or update dotfiles repository
          git:
            repo: https://github.com/italovieira/dotfiles.git
            dest: '{{ dotfiles_path }}'
            update: no
        - name: Put dotfiles symlinks in the target paths
          command:
            cmd: stow {{ item }}
            chdir: '{{ dotfiles_path }}'
          loop:
            - zsh
            - git
            - nvim
            - tmux
            - sway
            - waybar
