---
- name: Setup ArchLinux system
  hosts: localhost

  vars:
    dotfiles_path: ~/dotfiles/

  tasks:
    - name: Synchronize database and upgrade packages
      become: true
      pacman:
        update_cache: true
        upgrade: true

    - name: Install essential packages
      become: true
      pacman:
        name:
          # development
          - git
          - python
          - neovim
          - docker
          # DE
          - wayland
          - pipewire
          - sway
          - waybar
          - dunst
          # terminal
          - zsh
          - tmux
          - alacritty
          # browser
          - firefox
          # media
          - mpv
          # general
          - openssh
          - p7zip
          # extra
          - stow
        state: present

    - name: Setup dotfiles
      block:
        - name: Clone or update dotfiles repository
          git:
            repo: https://github.com/italovieira/dotfiles.git
            dest: "{{ dotfiles_path }}"
            update: no
        - name: Put dotfiles symlinks in the target paths
          command:
            cmd: stow {{ item }}
            chdir: "{{ dotfiles_path }}"
          loop:
            - zsh
            - git
            - nvim
            - tmux
            - sway
            - waybar
