---
- name: Setup Arch Linux system
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    dotfiles_path: ~/dotfiles/
    user: italo

  handlers:
    - import_tasks: handlers.yaml

  tasks:
    - name: Synchronize database and upgrade packages
      become: true
      pacman:
        update_cache: true
        upgrade: true

    - name: Install essential packages
      become: true
      pacman:
        name:
          - git
          - python
          - neovim
          - docker
          - wayland
          - pipewire
          - wireplumber
          - sway
          - waybar
          - dunst
          - zsh
          - tmux
          - alacritty
          - firefox
          - mpv
          - sudo
          - openssh
          - p7zip
          - stow
        state: present

    - tags: [user, never]
      block:
        - name: Setup sudo
          become: true
          lineinfile:
            path: /etc/sudoers.d/main
            line: '%wheel ALL=(ALL) ALL'
            mode: 0440
            create: yes
            validate: visudo --check --file %s

        - name: Create user
          become: true
          user:
            name: '{{ user }}'
            state: present
            groups:
              - wheel
              - docker
            append: yes
            generate_ssh_key: yes
            ssh_key_type: ed25519

    - name: Setup dotfiles
      block:
        - name: Clone dotfiles repository
          git:
            repo: https://github.com/italovieira/dotfiles.git
            dest: '{{ dotfiles_path }}'
            update: no
        - name: Put dotfiles symlinks in the target paths
          command:
            cmd: stow --verbose=2 {{ item }}
            chdir: '{{ dotfiles_path }}'
          loop:
            - zsh
            - git
            - nvim
            - tmux
            - sway
            - waybar
          register: stow
          changed_when: '"--- Skipping" not in stow.stderr'

    - name: Add Pipewire RNNoise input source
      copy:
        src: files/pipewire/source-rnnoise.conf
        dest: ~/.config/pipewire/pipewire.conf.d/
      notify: Restart pipewire
