---
- name: Setup Arch Linux system
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: config.yaml

  tasks:
    - name: Create temp directory for build tinted-theming colors
      tempfile:
        state: directory
        suffix: tinted-theming
      register: tinted_theming_tempdir

    - name: Download base16-builder-go
      get_url:
        url: https://github.com/tinted-theming/base16-builder-go/releases/download/v0.3.0/base16-builder-go_0.3.0_linux_amd64
        dest: '{{ tinted_theming_tempdir.path }}/base16-builder-go'
        mode: 0550

    - name: Generate base16 colors from some templates
      ansible.builtin.command:
        chdir: '{{ item.path }}'
        cmd: '{{ tinted_theming_tempdir.path }}/base16-builder-go'
      loop:
        - path: ~/.config/tinted-theming/.custom-templates/tmux
        - path: ~/.local/share/tinted-theming/tinty/repos/base16-waybar
        - path: ~/.local/share/tinted-theming/tinty/repos/base16-sway

    - name: Remove temp directory
      ansible.builtin.file:
        path: '{{ tinted_theming_tempdir.path }}'
        state: absent
      when: tinted_theming_tempdir.path is defined
